### PR TITLE
feat: add NIS currency

### PR DESCRIPTION
**Pull request by Araxeus**
NIS = New Israeli Shekel

> [!NOTE]
> This project lacks basic typescript .d.ts declaration file

### CODE REVIEW

**Comment by ozgurg** [comment]
Thanks for the contribution, and sorry for the delay.

According to Wikipedia, `NIS` is a non-ISO 4217 currency, but Google supports it (https://www.google.com/search?q=1+USD+to+NIS). So, we can add it.

I'll also add other non-ISO 4217 currencies, and then I'll merge this pull request.

Thanks again! This was the first contribution to this repo. 😊

**Comment by ozgurg** [comment]
Oh, I forgot. TypeScript definitions are not my priority currently because JSDoc will be sufficient for now. I will look into it when I have more time. I'm always open to contributions. :)

**Comment by Araxeus** [comment]
Anyone importing this package from a typescript file will get errors because of missing type declaration, and its very annoying to deal with

Typescript is very popular today, so it makes sense for a library to provide basic definition files :)

**Comment by ozgurg** [comment]
> Anyone importing this package from a typescript file will get errors because of missing type declaration, and its very annoying to deal with
> 
> Typescript is very popular today, so it makes sense for a library to provide basic definition files :)

I'm using TypeScript as well. I'll keep that in mind for future updates. Thanks again! 👍

**Pull request merged**
